### ISSUE TITLE
How to reproduce the IS/FID in the paper

### ISSUE THREAD

**Issue by sndnyang** [yilundu/improved_contrastive_divergence#3]
Thank you very much for sharing the idea/paper/code/pretrained-models.

But I encountered a difficulty.  I downloaded the model  from IGEBM https://github.com/openai/ebm_code_release  .  Then I installed the library as the requirements (I use tensorflow-gpu 1.12.0, not  cpu version)

And I ran  it  (I changed the filename model_74700.meta  to   model_74700.   )
```
python test_inception.py --logdir ~/Downloads/cachedir/ --exp cifar10_cond  --num_steps 20
```
I can't get a  correct  IS   just "Inception score of 2.01, FID of score 279", .   So, what's wrong with my command line argments?  

Thank you so much!

**Comment by yilundu** [comment]
Hi! Thanks for your question. Which repo are you using to compute the IS/FID scores? Is it the old OpenAI Repo or this github repo? For this github repo you will need to retrain the model in pytorch. I can give you the command to replicate the scores on the old repo if you are using the OpenAI repo.

**Comment by sndnyang** [comment]
The openai  one  https://github.com/openai/ebm_code_release/blob/master/test_inception.py 

Thank you so much !

**Comment by yilundu** [comment]
Sounds good! Can you reproduce the results if you run the command below?

`python test_inception.py --exp=<unconditional model experiment name> --num_steps=10 --batch_size=512 --step_lr=9.0 --resume_iter=121200 --im_number=1000 --repeat_scale=90 --scaled=False --noise_scale=0.005 --nomix=30 --large_model --ensemble=1`

**Comment by sndnyang** [comment]
Success!!! 

Inception score of 6.714271545410156 with std of 0.0

Thank you very much

**Comment by sndnyang** [comment]
Hi, I'm sorry for bothering you again

I can get the good Inception score  6.0 ~ 6.7 .  But the FID is 72   as the picture shows ,  seems much different from the  37.9  from the paper. 

Any reason about it?  The IGEBM/ openai  code. Thank you very much 

![image](https://user-images.githubusercontent.com/2310591/106363756-805e3080-62f8-11eb-8b7f-6d24fd9ec503.png)

**Comment by yilundu** [comment]
Hey, apologies its been a while since I've looked at the pretrained models in the paper. The code I used to reproduce the results of (37.9/6.78) utilizes 10 past models and is 

`python test_inception.py --exp=cifar10_large_network_smoke --num_steps=10 --batch_size=512 --step_lr=8.0 --resume_iter=121200 --im_number=50000 --repeat_scale=155 --scaled=False --noise_scale=0.005 --nomix=15 --large_model=True --ensemble=9 `

while I utilized this code to get 40.58 FID and 6.01 inception score is

`python test_inception.py --exp=cifar10_large_network_smoke --num_steps=10 --batch_size=512 --step_lr=9.0 --resume_iter=119700 --im_number=50000 --repeat_scale=80 --scaled=False --noise_scale=0.005 --nomix=10 --large_model --ensemble=1`

which is slightly different than the model that is released in the OpenAI repo. However I believe you should be available to get a bit lower FID using the lower command. Let me know if you have any other questions!

**Comment by sndnyang** [comment]
Thank you so much! I got 47.7 FID and 6.39 IS .
![image](https://user-images.githubusercontent.com/2310591/106373006-73b2fa00-6343-11eb-92db-760a5c11d1b1.png)
